apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: what3words-exercise

servers: 1
agents: 2

options:
  k3d:
    wait: true
    timeout: "120s"

  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
