apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: greeter
    meta.helm.sh/release-namespace: greeter-prod
  creationTimestamp: "2026-08-26T13:56:29Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: greeter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: greeter
    app.kubernetes.io/version: dev
    helm.sh/chart: greeter-0.1.0
  name: greeter-greeter
  namespace: greeter-prod
  resourceVersion: "23213"
  uid: 41de4fa6-726c-4546-b223-6ced8122e9da
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: greeter
      app.kubernetes.io/name: greeter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: greeter
        app.kubernetes.io/name: greeter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - env:
        - name: GREETING_NAME
          value: what3words Production
        - name: PORT
          value: "8080"
        - name: VERSION
          value: prod
        - name: WARMUP_SECONDS
          value: "30"
        - name: SHUTDOWN_DELAY_SECONDS
          value: "10"
        - name: DRAIN_TIMEOUT_SECONDS
          value: "20"
        image: greeter:exercise
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: greeter
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 40
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: greeter
            app.kubernetes.io/name: greeter
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2026-08-26T13:56:29Z"
    lastUpdateTime: "2026-08-26T14:16:45Z"
    message: ReplicaSet "greeter-greeter-5f4b5484cd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-08-27T14:35:53Z"
    lastUpdateTime: "2026-08-27T14:35:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  terminatingReplicas: 0
  updatedReplicas: 2
