grafana:
  enabled: false

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 2h

    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    serviceMonitorNamespaceSelector: {}
    ruleNamespaceSelector: {}
